#!/bin/bash

for FILE in $HOME/data/dune/adc/DUNE17dla/*_cold/adcDavidAdamsOnlyData*; do
  FNAME=`basename $FILE`
  DAY=`echo $FNAME | awk -F _ '{print $2}' | sed 's/^20..//g'`
  CHIP=`echo $FNAME | awk -F _ '{print $3}'`
  TRY=`echo $FNAME | sed 's/.*_//g' | sed 's/\..*//g'`
  SNAME="DUNE17dla-cold_${CHIP}_${DAY}_${TRY}"
  echo $SNAME
done
